### PR TITLE
Quick Start Guide

### PR DESCRIPTION
**Pull request by barberw-OSU**
A Quick Start Guide specifically for Covidify and how to get started in the Mac environment using Anaconda.

### CODE REVIEW

**Comment by AaronWard** [comment]
Thanks very much for this, but would you be able to change the location to be inside the resources folder? 😄

**Comment by barberw-OSU** [comment]
Absolutely I will re-submit in just a second.  Thank you.

**Comment by barberw-OSU** [comment]
Moved quick start guide to resources folder

**Comment by AaronWard** [comment]
LGTM 😄 Thanks!

**Pull request merged**
